# Generated by Django 4.0.4 on 2022-05-26 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colBox', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imageCategory',
            field=models.ManyToManyField(to='colBox.category'),
        ),
    ]
