# Generated by Django 4.0.4 on 2022-05-27 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colBox', '0003_remove_image_imagecategory_image_imagecategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageCategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colBox.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageLocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='colBox.location'),
        ),
    ]
