# Generated by Django 4.0.4 on 2022-05-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colBox', '0004_alter_image_imagecategory_alter_image_imagelocation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imageCategory',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
