# Generated by Django 4.0.4 on 2022-05-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colBox', '0005_remove_image_imagecategory_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='imageCategory',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='colBox.category'),
        ),
    ]
