# Generated by Django 4.0.4 on 2022-05-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colBox', '0006_category_image_imagecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Food', 'Food'), ('Cars', 'Cars'), ('Shoes', 'Shoes'), ('Quotes', 'Quotes')], max_length=40),
        ),
    ]
